config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/home', to: 'home#index'
  resources :boards
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'boards#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
# frozen_string_literal: true

class Board < ApplicationRecord
  has_many :mine_cells, dependent: :delete_all

  # maximum of the board's width and height
  MAX_WIDTH = 1000

  validates :creator_email, :name, :width, :height, :mines_num, presence: true
  validates_format_of :creator_email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :width, :height, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: MAX_WIDTH }
  validates :mines_num, numericality: {
    only_integer: true, greater_than: 0, less_than_or_equal_to: ->(board) { board.width * board.height }
  }, if: -> { width && width.positive? && height && height.positive? }

  def self.search(term)
    if term
      where('name ILIKE ? OR creator_email ILIKE ?', "%#{term}%", "%#{term}%")
    else
      all
    end
  end
end

app/models/mine_cell.rb
# frozen_string_literal: true

class MineCell < ApplicationRecord
  belongs_to :board

  validates :x, :y, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

class BoardsController < ApplicationController
  before_action :set_board, :redirect_when_not_found, only: %i[show edit update destroy]

  def index
    @pagy, @boards = pagy(Board.search(params[:term]).order(created_at: :desc), items: 5)
  end

  def show
    @all_cells = AllCellsGenerator.new(board: @board).call
  end

  def new
    @board = Board.new
  end

  def create
    board = BoardCreator.new(board_params).call
    redirect_to board, notice: 'Board was successfully created.'
  rescue StandardError => e
    flash.now[:alert] = e.message
    @board = Board.new(board_params)
    render :new, status: :unprocessable_entity
  end

  def destroy
    @board.destroy
    redirect_to boards_url, notice: 'Board was successfully destroyed.'
  rescue StandardError => e
    redirect_to boards_url, alert: e.message
  end

  private

  def set_board
    @board = Board.find_by(id: params[:id])
  end

  def redirect_when_not_found
    redirect_to '/404' if @board.blank?
  end

  def board_params
    params.require(:board).permit(:creator_email, :name, :width, :height, :mines_num, :term)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @boards = Board.order(created_at: :desc).limit(5)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/views/boards/_form.html.erb
<%= form_with(model: board, class: "contents", data: { turbo: false }) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :creator_email %>
    <%= form.text_field :creator_email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :width %>
    <%= form.number_field :width, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :height %>
    <%= form.number_field :height, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :mines_num %>
    <%= form.number_field :mines_num, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit "Generate board", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/boards/index.html.erb
<div class="w-full flex flex-col">
  <div>
    <%= link_to '< Back to home', home_path, class: "rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium" %>
    <%= link_to 'New board', root_path, class: "rounded-lg py-3 px-5 bg-green-600 text-white inline-block font-medium" %>
  </div>

  <div class="my-5">
    <h1 class="font-bold text-4xl">All boards</h1>
  </div>

  <div class="my-5 text-right">
    <%= form_tag(boards_path, method: :get) do %>
      <%= text_field_tag :term, params[:term], placeholder: 'by name or email...' %>
      <%= submit_tag 'Search', class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    <% end %>
  </div>

  <div id="boards" class="overflow-auto">
    <% if @boards.length > 0 %>
      <% @boards.each do |board| %>
        <%= render partial: 'shared/board', locals: { board: board } %>
      <% end %>
    <% else %>
      (No data available)
    <% end %>
  </div>

  <% if @boards.length > 0 %>
    <div class="my-5 text-blue-600 text-center">
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="w-full flex flex-col">
  <div>
    <%= link_to '< Back to home', home_path, class: "rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium" %>
    <%= link_to 'View all generated boards', boards_path, class: "rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium" %>
  </div>

  <div class="my-5">
    <h1 class="font-bold text-4xl">New board</h1>
  </div>

  <div class="overflow-auto">
    <%= render "form", board: @board %>
  </div>
</div>

app/views/boards/show.html.erb
<div class="w-full flex flex-col">
  <div>
    <%= link_to '< Back to home', home_path, class: "rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium" %>
    <%= link_to 'Destroy this board', board_path(@board), data: {turbo_method: :delete}, class: "rounded-lg py-3 px-5 bg-red-100 text-red-500 inline-block font-medium" %>
  </div>

  <div class="my-5">
    <h1 class="font-bold text-4xl">Details</h1>
  </div>

  <div>
    <div class="text-blue-500 text-xl">
      <%= @board.name %>
    </div>
    <div>
      <%= @board.creator_email %>
    </div>
    <div>
      Size: <%= @board.width %> x <%= @board.height %> (with <%= @board.mines_num%> mines)
    </div>
    <br/>
  </div>

  <div class="w-full h-full overflow-hidden">
      <div class="w-full h-full overflow-auto">
        <table class="border-collapse">
          <% @board.height.times.each do |y| %>
            <tr>
              <% @board.width.times.each do |x| %>
                <% if @all_cells[[x, y]] %>
                  <td class="w-8 min-w-8 h-8 min-h-8 border-solid bg-red-600 border-4 text-center">
                    <i class="fa fa-bomb"></i>
                  </td>
                <% else %>
                  <td class="w-8 min-w-8 h-8 min-h-8 border-solid border-4 text-center"></td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        </table>
      </div>
  </div>
  
</div>

app/views/home/index.html.erb
<div class="w-full flex flex-col">
  <div>
    <%= link_to 'View all generated boards', boards_path, class: "rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium" %>
    <%= link_to 'New board', root_path, class: "rounded-lg py-3 px-5 bg-green-600 text-white inline-block font-medium" %>
  </div>

  <div class="my-5">
    <h1 class="font-bold text-4xl">Recent boards</h1>
  </div>

  <div id="boards" class="overflow-auto">
    <% if @boards.length == 0 %>
      (No data available)
    <% else %>
      <% @boards.each do |board| %>
        <%= render partial: 'shared/board', locals: { board: board } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <p class="w-full py-2 px-3 font-medium rounded-lg inline-block text-center <%= type == 'alert' ? 'bg-red-50 text-red-500' : 'bg-green-50 text-green-500' %>">
        <%= msg %>
      </p>
    <% end %>

    <main class="container mx-auto p-5 flex h-screen">

      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_board.html.erb
<div id="<%= dom_id board %>">
  <div class="flex justify-between items-center">
    <div class="text-blue-500 pr-8 text-xl">
      <%= link_to board do %>
        <%= board.name %>
      <% end %>
    </div>

    <div class="italic">
      <%= time_ago_in_words(board.created_at) %>
    </div>
  </div>
      <div>
      <%= board.creator_email %>
    </div>
  <hr class="my-5">
</div>